### ISSUE TITLE
helditem unable to work normally

### ISSUE THREAD

**Issue by bfwqzj** [McJty/InControl#172]
"random":0.01,
    "dimension":0,
    "mob": ["minecraft:skeleton"],
    "result":"allow",
	
   "armorhelmet":[{"item": "minecraft:skull","damage":"0"}],
   "armorchest":["minecraft:chainmail_chestplate"],
   "armorlegs":["minecraft:arrow"],
   "armorboots":["minecraft:arrow"],
   "helditem":[{"item":"minecraft:stone_sword","Count":"1"}],

    "healthmultiply": 0.3,
    "damagemultiply": 1,
    "speedmultiply": 1.25,
	
   "potion": "minecraft:invisibility,10000,1"
The resulting skeleton does not hold the stone sword properly please help me

If possible please answer me another question blaze cannot spawn on lava
 {
    "dimension":0,
   "maxheight":20,
   “ block”:“minecraft：lava”，
   "mobs":[{
   "mob":["minecraft:blaze"],
   "weight": 1,
    "groupcountmin": 1,
    "groupcountmax": 1
  }]}

**Comment by Enderkitty9** [comment]
As of 1.12.2 skeletons will not hold a stated item because they are already given a bow

I believe the issue with the blazes on lava is there may be a space in the ID where there shouldn't:
minecraft: lava = no
minecraft:lava = yes

The brackets you are using look strange, so if they are wearing the armor provided (they should) then you are fine, but if they aren't check these examples:
[(older version)](https://wiki.mcjty.eu/mods/index.php?title=InControl)
[(newer version)](https://wiki.mcjty.eu/mods/index.php?title=ControlMods)
If it still seems to not work check your JSon [here](https://jsonlint.com/)

note- I am not the mod creator of either mod, so I'm not sure what version you are using

**Comment by property-owner** [comment]
using "onjoin": true fixes this!
